apiVersion: v1
kind: Service
metadata:
  name: {experimentName}
  namespace: {namespaceName}
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: {experimentName}