name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/MLOps.NET/MLOps.NET.sln
    - name: Build
      run: dotnet build src/MLOps.NET/MLOps.NET.sln --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src/MLOps.NET/MLOps.NET.sln --configuration Release --no-build
